version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: prueba
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
